services:
  keep-frontend:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    environment:
      - AUTH_TYPE=NO_AUTH
      - API_URL=http://keep-backend:8080
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api
    environment:
      - AUTH_TYPE=NO_AUTH
      - REDIS=true
      - REDIS_HOST=keep-arq-redis
      - REDIS_PORT=6379
    volumes:
      - ./state:/state
      - ./migrations:/migrations
    depends_on:
      - keep-arq-redis

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common

  keep-arq-redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8081:8001"

  keep-arq-dashboard:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-arq-dashboard
    ports:
      - "8082:8000"
    entrypoint:
        - "uvicorn"
        - "--host"
        - "0.0.0.0"
        - "arq_dashboard:app"
    environment:
      - ARQ_DASHBOARD_REDIS_URL=redis://keep-arq-redis:6379
