version: "3.9"

services:
  mysql:
    image: mysql:latest
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: keep-keycloak
    ports:
      - 8181:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_ADMIN: keep_kc
      KEYCLOAK_ADMIN_PASSWORD: keep_kc
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HTTP_RELATIVE_PATH: /auth
      # this will be used in keep-realm.json
      KEEP_REALM: keep
      KEEP_ADMIN_USER: keep_admin # default admin user for keep
      KEEP_ADMIN_PASSWORD: keep_admin # default admin password for keep
      KEEP_TENANT_ID: keep # default single tenant id for keep
      KEEP_AUTH_REDICERT_URL: http://localhost:3000/*
      KEEP_CLIENT_ID: keep
      KEEP_KEYCLOAK_SECRET: keep-keycloak-secret
      KEYCLOAK_DEBUG: false # used in entrypoint
    entrypoint: ["/opt/keycloak/keycloak_entrypoint.sh"]
    volumes:
      - ./keep-realm.json:/opt/keycloak/data/import/keep-realm.json
      - ./themes/keep.jar:/opt/keycloak/providers/keep.jar
      - ./event_listeners/last-login-event-listener-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-event-listener.jar
      # - ./javascript_providers/keep-js-policies.jar:/opt/keycloak/providers/keep-js-policies.jar
      - ./keycloak_entrypoint.sh:/opt/keycloak/keycloak_entrypoint.sh
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "Keep Organization"
      LDAP_DOMAIN: "keep.com"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_BASE_DN: ""
    volumes:
      - openldap-data:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    networks:
      - keycloak-and-mysql-network

  ldap-ui:
    image: dnknth/ldap-ui
    ports:
      - "8081:5000"
    environment:
      LDAP_URL: "ldap://openldap:389"
      BASE_DN: "dc=keep,dc=com"
      BIND_DN: "cn=admin,dc=keep,dc=com"
      BIND_PASSWORD: "admin_password"
    depends_on:
      - openldap
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
  openldap-data:
  openldap-config:
