{{- if .Values.backend.route.enabled -}}
{{- $fullName := include "keep.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels: {{- include "keep.labels" . | nindent 4 }}
spec:
  host: {{ .Values.backend.route.host }}
  to:
    kind: Service
    name: {{ $fullName }}-backend
    weight: 100
  port: 
    targetPort: {{ .Values.backend.service.port }}
  wildcardPolicy: {{ .Values.backend.route.wildcardPolicy }}
  tls: 
  {{ toYaml .Values.backend.route.tls | indent 4 }} 
{{- end}}