apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
kind: ServiceAccount
  name: secret-manager
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
