apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep.fullname" . }}-websocket
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    keep-component: websocket-service
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keep.selectorLabels" . | nindent 4 }}
    keep-component: websocket
